describe('CyEditor E2E', () => {
    const mockNetwork = {
        version: '1.0.0',
        cycle: 0,
        nodes: [
            {
                node_id: 0,
                node_name: 'Node_0',
                node_features: ['cache'],
                display: {
                    id: 'node-0',
                    label: 'N0',
                    type: '*node.WorkerNode',
                    position: { x: 100, y: 100 }
                }
            },
            {
                node_id: 1,
                node_name: 'Node_1',
                node_features: ['cache'],
                display: {
                    id: 'node-1',
                    label: 'N1',
                    type: '*node.WorkerNode',
                    position: { x: 300, y: 100 }
                }
            }
        ],
        edges: [
            {
                edge_id: 1,
                src_node_id: 0,
                dst_node_id: 1,
                src_port_id: 0,
                dst_port_id: 0,
                latency: 10,
                bandwidth: 1,
                packet_types: [1, 2],
                display: {
                    lineType: 'solid'
                    // source/target/id automatically generated by mapper based on node IDs
                }
            }
        ]
    }

    beforeEach(() => {
        // Mock Backend API
        cy.intercept('GET', '/load_networks', [mockNetwork]).as('loadNetworks')
        cy.intercept('GET', '/ws', { statusCode: 200 }).as('ws')

        cy.visit('/')

        // Wait for network to be loaded
        cy.wait('@loadNetworks')

        // App.vue exposes window.testCy when ready
        cy.window().should('have.property', 'testCy')
    })

    it('should load the editor and render canvas', () => {
        cy.get('canvas').should('exist')
        cy.wait(500)
    })

    it('programmatically select node should show node panel', () => {
        cy.window().then((win) => {
            const core = win.testCy
            const nodes = core.nodes()
            nodes[0].select()
        })

        cy.get('.empty-state').should('not.exist')
        cy.get('.property-section').should('exist')
        // Verify Node Property Panel Title
        cy.contains('h3', 'Node 0 Properties').should('exist')
        cy.get('.jsoneditor').should('exist')
        cy.wait(500)
    })

    it('programmatically select edge should show edge panel', () => {
        cy.window().then((win) => {
            const core = win.testCy
            const edges = core.edges()
            expect(edges.length).to.be.greaterThan(0)
            edges[0].select()
        })

        cy.get('.empty-state').should('not.exist')
        // Verify Edge Property Panel Title
        cy.contains('h3', 'Edge 1 Properties').should('exist')
        cy.get('.jsoneditor').should('exist')
        cy.wait(500)
    })

    // Known limitation: Dragging on Canvas via Cypress is tricky due to event coordinates
    // We will simulate the drag event programmatically on the node to verify data sync
    it('programmatically drag node should update vue model', () => {
        cy.window().then((win) => {
            const core = win.testCy
            const node = core.nodes()[0]
            const oldPos = { ...node.position() }
            const newPos = { x: oldPos.x + 50, y: oldPos.y + 50 }

            // Check initial state in Vue
            const app = win.app
            // We can't easily check app.latestNetwork here because it might likely be deeply nested or processed
            // But we can monitor the event or check if 'drag' changes position in cytoscape

            // Simulating drag:
            if (node.locked()) {
                cy.log('Node was locked, unlocking...')
                node.unlock()
            }
            node.position(newPos)

            // Debug: Check if position changed
            if (node.position().x !== 150) {
                // Try individual set
                node.position('x', 150)
                node.position('y', 150)
                if (node.position().x !== 150) {
                    throw new Error(`Immediate position set failed even after unlock/retry. Locked: ${node.locked()}. Pos: ${JSON.stringify(node.position())}`)
                }
            }

            // Cytoscape internal state update
            node.emit('drag')

            if (node.position().x !== 150) {
                throw new Error(`Position reset after emit('drag'). Expected 150, got ${node.position().x}`)
            }

            // Important: emit dragfree to trigger CyEditor listener which emits 'node-drag-end'
            node.emit('dragfree')

            if (node.position().x !== 150) {
                throw new Error(`Position reset after emit('dragfree'). Expected 150, got ${node.position().x}`)
            }

            // Vue update might happen asynchronously
        })

        // Retry assertion until Vue updates
        cy.window().then((win) => {
            return new Cypress.Promise((resolve) => {
                // Poll for update or wait
                setTimeout(() => {
                    resolve(win)
                }, 1500)
            })
        }).should((win) => {
            const app = win.app
            const nodes = app.latestNetwork.nodes
            const nodeJson = nodes.find(n => n.node_id === 0)

            if (nodeJson.display.position.x !== 150) {
                const internalState = win.app.$refs.demoEditor.cyEditor.networkState
                const internalNode = win.testCyEditor.networkState.nodes.find(n => n.node_id === 0)

                if (internalNode && internalNode.display.position.x === 150) {
                    throw new Error(`Internal networkState HAS updated (150), but app.latestNetwork is stale (100). Event Bus or Wrapper issue?`)
                } else if (internalNode && internalNode.display.position.x !== 150) {
                    const logs = win.cyLogs ? win.cyLogs.join('\n') : 'No logs captured in window.cyLogs'
                    throw new Error(`Internal networkState is ALSO stale (${internalNode.display.position.x}). DisplayToNetwork issue? Node ID: 0\nCaptured Logs:\n${logs}`)
                } else {
                    throw new Error(`Internal networkState Node 0 NOT FOUND.`)
                }
            }

            // networkMapper maps position to display.position
            expect(nodeJson.display.position.x).to.equal(150)
            expect(nodeJson.display.position.y).to.equal(150)
        })
        cy.wait(500)
    })

    it('websocket message should update network', () => {
        const newCycleData = JSON.parse(JSON.stringify(mockNetwork))
        newCycleData.cycle = 100
        newCycleData.nodes[0].display.position.y = 200 // Move node 0 via backend update

        cy.window().then((win) => {
            const app = win.app
            // Trigger WS message
            const event = { data: JSON.stringify(newCycleData) }
            app.ws.onmessage(event)
        })

        // Verify Vue model is updated
        cy.window().should((win) => {
            const app = win.app
            expect(app.latestNetwork.cycle).to.equal(100)

            // Verify position update is reflected in model
            const node0 = app.latestNetwork.nodes.find(n => n.node_id === 0)
            expect(node0.display.position.y).to.equal(200)
        })
        cy.wait(500)

        // Verify Canvas is updated (check position in Cy)
        cy.window().then((win) => {
            const cy = win.testCy
            // Note: App.vue only calls loadNetwork if we explicitly ask, 
            // OR checks if it should update.
            // In App.vue: "this.networkValue = data; this.latestNetwork = data;"
            // But commented out: "// 不调用 loadNetwork，只更新必要的状态数据"
            // So onmessage DOES NOT update the canvas layout to avoid resetting user view!
            // This is intentional behavior.

            // So we should expect Cy model to NOT change position unless custom logic exists?
            // "this.networkValue = data" -> passed to <cy-editor :network="networkValue">
            // CyEditor watches generic 'network' prop?
            // Need to check CyEditor.js or wrapper if it watches 'network'.

            // Checking App.vue template: :network="networkValue" @network-change...
            // Checking CyEditor.vue (wrapper)? No, CyEditor is JS class.
            // Ah, <cy-editor> component in App.vue likely wraps the class.
        })
    })
})

