/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/load_networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 返回所有网络 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description FlowSimNetwork 列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FlowSimNetwork"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/build_network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 根据 FlowSimNetwork 构建仿真网络 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FlowSimNetwork"];
                };
            };
            responses: {
                /** @description 构建成功，返回规范化的 FlowSimNetwork */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FlowSimNetwork"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reset_network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重置仿真，把网络重置为给定 FlowSimNetwork */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FlowSimNetwork"];
                };
            };
            responses: {
                /** @description 重置后的 FlowSimNetwork */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FlowSimNetwork"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advance_to": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 仿真到指定 cycle */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 目标仿真周期 */
                        cycle: number;
                    };
                };
            };
            responses: {
                /** @description 返回更新后的网络状态 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FlowSimNetwork"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/current_state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前网络状态（用于轮询） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 当前 FlowSimNetwork 状态 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FlowSimNetwork"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate_network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 验证网络配置合法性 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FlowSimNetwork"];
                };
            };
            responses: {
                /** @description 验证结果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            valid: boolean;
                            errors?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/save_network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 保存网络到文件 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 文件名 */
                        name: string;
                        network: components["schemas"]["FlowSimNetwork"];
                    };
                };
            };
            responses: {
                /** @description 保存成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 保存的文件路径 */
                            path?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/load_preset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 加载预设网络拓扑 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 预设名称 */
                        name: string;
                        /** @description 预设参数 */
                        params?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description 加载成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FlowSimNetwork"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Flow Simulation 网络定义，包含拓扑、配置、状态和可视化信息 */
        FlowSimNetwork: {
            /**
             * @description Schema 版本号
             * @example 1.0.0
             */
            version?: string;
            /**
             * @description 当前仿真周期
             * @example 0
             */
            cycle?: number;
            /** @description 节点列表 */
            nodes: components["schemas"]["Node"][];
            /** @description 边列表 */
            edges: components["schemas"]["Edge"][];
            /** @description 可选：视图缩放级别（CyEditor） */
            zoom?: number;
            /** @description 可选：视图平移（CyEditor） */
            pan?: {
                x?: number;
                y?: number;
            };
        };
        /** @description 网络节点，兼容 CyEditor 格式 */
        Node: {
            /** @description 节点唯一标识符 */
            node_id: number;
            /** @description 节点名称 */
            node_name: string;
            /** @description 节点特性列表，如 ['cpu', 'cache'] */
            node_features?: string[];
            /** @description 输入端口列表 */
            in_ports?: components["schemas"]["Port"][];
            /** @description 输出端口列表 */
            out_ports?: components["schemas"]["Port"][];
            cache?: components["schemas"]["CacheConfig"];
            directory?: components["schemas"]["DirectoryConfig"];
            /** @description 一致性域 ID */
            coherence_domain_id?: number;
            /** @description CyEditor data 字段，存储节点元数据 */
            data: {
                /** @description Cytoscape 节点 ID（通常为 'node-{node_id}'） */
                id: string;
                /** @description 节点类型（用于渲染） */
                type?: string;
                /** @description 节点显示标签 */
                label?: string;
            } & {
                [key: string]: unknown;
            };
            /** @description CyEditor position 字段 */
            position: {
                x: number;
                y: number;
            };
            /** @description Cytoscape 样式 */
            style?: {
                [key: string]: unknown;
            };
        };
        /** @description 端口定义，包含配置和运行时状态 */
        Port: {
            /** @description 端口 ID */
            port_id: number;
            /** @description 带宽（配置） */
            bandwidth: number;
            /** @description 缓冲区大小（配置） */
            buffer_size?: number;
            /** @description 支持的包类型 */
            packet_types?: number[];
            /** @description 当前缓冲区使用量 */
            buffer_length?: number;
            /** @description 缓冲区容量（别名，与 buffer_size 相同） */
            capacity?: number;
            /** @description 缓冲区占用位图，如 '1010...' */
            bitmap?: string;
        };
        /** @description 缓存配置和统计 */
        CacheConfig: {
            /** @description 缓存容量（字节） */
            capacity: number;
            /** @description 缓存组数 */
            num_sets: number;
            /**
             * @description 替换策略
             * @enum {string}
             */
            replacement_policy: "LRU" | "FIFO" | "Random" | "LFU";
            /**
             * @description 一致性状态协议
             * @example MESI
             */
            states: string;
            /** @description 缓存命中次数 */
            hits?: number;
            /** @description 缓存未命中次数 */
            misses?: number;
            /** @description 总访问次数 */
            accesses?: number;
        };
        /** @description 目录配置 */
        DirectoryConfig: {
            capacity: number;
            num_sets: number;
            replacement_policy: string;
            states: string;
        };
        /** @description 连接两个节点的边，兼容 CyEditor 格式 */
        Edge: {
            /** @description 边唯一标识符 */
            edge_id: number;
            /** @description 源节点 ID */
            src_node_id: number;
            /** @description 源端口 ID */
            src_port_id?: number;
            /** @description 目标节点 ID */
            dst_node_id: number;
            /** @description 目标端口 ID */
            dst_port_id?: number;
            /** @description 链路延迟（周期） */
            latency?: number;
            /** @description 链路带宽 */
            bandwidth?: number;
            /** @description 支持的包类型 */
            packet_types?: number[];
            /** @description CyEditor data 字段 */
            data: {
                /** @description Cytoscape 边 ID（通常为 'edge-{edge_id}'） */
                id: string;
                /** @description 源节点 data.id */
                source: string;
                /** @description 目标节点 data.id */
                target: string;
                /**
                 * @description 线条类型
                 * @enum {string}
                 */
                lineType?: "solid" | "dashed" | "taxi";
            } & {
                [key: string]: unknown;
            };
            /** @description 链路占用状态 */
            link_status?: {
                /** @description 状态名称（如 'occupancy'） */
                name: string;
                /** @description 每个时间槽的占用情况 */
                values: number[];
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
